name: genbindings

on:
  push:
    branches:
      dev/*
      release/*
    paths-ignore:
      - '**.md'
      - '**/*.md.in'
      - 'docs/**'
      - '.github/workflows/publish.yml'
      - 'tools/ci/make-pkg.ps1'

  workflow_dispatch:
jobs:
  genbindings:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.5'

    - name: Genbindings
      run: tools\ci\genbindings.ps1

    - name: Create pull request
      if: ${{ env.BINDING_NO_CHANGES != 'true' }}
      id: cpr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.AX_BOT_TOKEN }}
        push-to-fork: axmol-bot/axmol
        commit-message: Committing luabindings for commit ${{ env.LAST_COMMIT_HASH }}
        signoff: false
        branch: luabindings_for_${{ env.LAST_COMMIT_HASH }}
        delete-branch: true
        title: 'Committing luabindings for commit ${{ env.LAST_COMMIT_HASH }}'
        body: |
          RT
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        labels: |
          lua-bindings
          automated pr
          pinned
        assignees: axmol-bot
        reviewers: halx99
        draft: false

    - name: Check outputs
      if: ${{ steps.cpr.outputs.pull-request-number }}
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
